### PR TITLE
added pbtestkit-service-* commands (moved from pysiv2)

### PR DESCRIPTION
**Pull request by natechols**

### CODE REVIEW

**Comment by natechols** [comment]
@mpkocher this look okay?  wasn't sure where to put some of the utility functions in service_runner.py

**Comment by mpkocher** [comment]
Looks good. This enables running jobs at both just the command line or the services from a testkit.cfg, which is going to be really valuable. 

You have a comment about the logging for the multi case. I assume this is to have the log files separate for each job (similar to how the non-service driven model works)?

In retrospect, I think merging the runner and multi-runner into one cli tool would be a longer term goal (similarly for the pbtestkit-server-* ) Do you see any issues with this?

**Comment by natechols** [comment]
Yes, I just want to avoid a log pileup on the console.  Presumably this is straightforward but I don't know the appropriate way to do it.

I agree that unifying the test runners would be valuable.  Perhaps we could go even further and merge execution-via-services into pbtestkit-runner as well, e.g.:

    $ pbtestkit-runner --services --host http://localhost --port 8070 testkit.cfg

This might be overkill - the current code seems very redundant though.

**Comment by mpkocher** [comment]
Yeah.. this might be overkill. Going from 4 exes to 2 seems like a reasonable compromise. 

Creating a new issue to track this.

**Pull request merged**
