### PR TITLE
Eliminate warning

### PR DESCRIPTION
**Pull request by pb-cdunn**
[ERROR] 2016-02-08 16:47:55,286Z   warnings.warn("log_filter kw is no longer supported")

### CODE REVIEW

**Comment by natechols** [comment]
@mpkocher i've been seeing the same error, if you have an alternative fix please comment, otherwise i vote yay

**Comment by mpkocher** [comment]
Change it to log.warn

**Comment by pb-cdunn** [comment]
But keep using `log_filter`?

**Comment by mpkocher** [comment]
Or delete the warning.

**Comment by pb-cdunn** [comment]
But should `log_filter` still be used?

**Comment by mpkocher** [comment]
This entire model is planned to be deprecated in favor of the global logging setup configuration model.

https://github.com/PacificBiosciences/pbcommand/blob/master/pbcommand/utils.py#L179

My suggestion is to fix the problem at the root cause in pbcommand. Call setup_logger first, then log the warning if the filter is not None. Does this seem reasonable?

**Comment by pb-cdunn** [comment]
A one-liner to suppress a warning (shown as ERROR) versus a bunch of work for something deprecated anyway. I'll just ignore the ERROR WARNING or whatever for now. No big deal. Thought I was doing you a favor!

**Comment by mpkocher** [comment]
https://github.com/PacificBiosciences/pbcommand/commit/a8b90fa7a328db95a2e4aaf78932ad2f436c7b75

**Pull request closed without merging**
