### PR TITLE
Update versions of TCs for falcon

### PR DESCRIPTION
**Pull request by pb-cdunn**
This is nothing but version updates for the latest pbcommand, but it fails. Why?

### CODE REVIEW

**Comment by mpkocher** [comment]
This is empty.

https://github.com/pb-cdunn/pbsmrtpipe/blob/e2ae979c8b164838cb48b6dae9576b6c1bc64084/pbsmrtpipe/registered_tool_contracts_sa3/upgrade_tool_contract.json

**Comment by pb-cdunn** [comment]
Then I need help with how to update tool-contracts. Something has changed.

**Comment by pb-cdunn** [comment]
```
python -m pbfalcon.tasks.basic emit-tool-contracts
python -m pbfalcon.tasks.scatter0_run_daligner_jobs --emit-tool-contract >| pbfalcon.tasks.scatter0_run_daligner_jobs_tool_contract.json
python -m pbfalcon.tasks.scatter1_run_daligner_jobs --emit-tool-contract >| pbfalcon.tasks.scatter1_run_daligner_jobs_tool_contract.json
python -m pbfalcon.tasks.gather0_run_daligner_jobs --emit-tool-contract >| pbfalcon.tasks.gather0_run_daligner_jobs_tool_contract.json
python -m pbfalcon.tasks.gather1_run_daligner_jobs --emit-tool-contract >| pbfalcon.tasks.gather1_run_daligner_jobs_tool_contract.json
```

**Comment by mpkocher** [comment]
My guess is that your custom post processing of the TCs is creating an empty file?

**Comment by mpkocher** [comment]
This `python -m pbfalcon.tasks.basic emit-tool-contracts` needs to be redirected to a dir. It's a list.

**Comment by pb-cdunn** [comment]
Hmm. I don't know where that file came from. But I've removed it from these PRs. Let's see if that's enough.

**Comment by pb-cdunn** [comment]
> This `python -m pbfalcon.tasks.basic emit-tool-contracts` needs to be redirected to a dir. It's a list.

I copy the files after creating them. Maybe that's what you mean.

I don't directly install the TCs because I canonicalize the JSON first -- sorting and removing all trailing whitespace (which is added by the standard JSON dumper).

**Pull request merged**
