### PR TITLE
update variantCaller TC

### PR DESCRIPTION
**Pull request by ben-lerch**
To address SAT-461 and SL-428

### CODE REVIEW

**Comment by natechols** [comment]
you'll need to modify the chunk operator to include an additional FASTA gather.

**Comment by natechols** [comment]
Uh-oh... I just realized that this isn't going to work for the pipeline, because it will split up the contigs and they need to be reassembled.  The ContigSet gather does this, but not the FASTA gather.  Maybe we'd be better off scrapping this and adding a redundant pass-through task that takes the gathered ContigSet as input and "outputs" the underlying FASTA.

**Comment by ben-lerch** [comment]
Ok, I'll work on that.

**Comment by mpkocher** [comment]
@natechols  is the longer term solution that tools need to polymorphically support input and output of a ContigSet or Fasta?

**Comment by natechols** [comment]
This is entirely driven by marketing's request to expose the FASTA on the download page instead of a ContigSet, so I'm not sure if we need a long-term solution or not, or what it would look like.

**Comment by ben-lerch** [comment]
I think marketing wants to have the freedom to ask that any file be exposed in the UI. So I think we need a general solution for that. Having a contigset-to-fasta task seems a bit ad-hoc (the fasta file is already there).

**Comment by natechols** [comment]
What marketing is asking is already ad-hoc and imposes significant technical overhead.  We can't expose arbitrary output files in the UI without adding them to tool contracts and implementing the necessary gather task(s).  That's a lot of work and in this particular case duplicates what is already being handled internally.

**Comment by mpkocher** [comment]
I believe the fundamental issue is that we have defined an XML metadata container (e.g., PacBio DataSet) that has external resources. Downloading a SubreadSet, ReferenceSet, ContigSet, etc... via SL is only useful if you have accesses to the file system with the external resources. Hence, there's a request to access the external resource(s) instead of the container metadata file.

The UI could grab the external resources from /{dataset-type}/{uuid}/details and get the external resources, then provide download links for the files. However, the external resources referenced in the original DataSet would have to be made relative to where these files are written. 

The other friction point is that some tools are missing compatibility for datasets as first class citizens, which results in translation layers at the pipeline level.

**Pull request closed without merging**
