### PR TITLE
Clean-up run_command*

### PR DESCRIPTION
**Pull request by pb-cdunn**
Rebased.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Oh, btw, without this change, I think the stdout/err of some procs go into the top run-dir, not under job_output.

**Comment by pb-cdunn** [comment]
@mpkocher,

I see one problem. pbsmrtpipe/REQUIREMENTS.txt has this:

    3 pbcore <= 1.2.4
    4 pbcommand <= 0.2.15

CircleCI is using *both* PB_REQUIREMENTS.txt *and* REQUIREMENTS.txt. The tip of master for pbcommand in GitHub has this:

    pbcommand/__init__.py:VERSION = (0, 2, 16)

See the problem? The CircleCI build is not using the GitHub version of
pbcommand.

**Comment by mpkocher** [comment]
Nat and I discussed this yesterday. Clearly, pbsmrtpipe doesn't support pbcore 0.1.0 nor pbcommand 0.1.0.

https://github.com/mpkocher/pbsmrtpipe/commit/aec9ce3e0b3cefbc7275023b043cba4036652d85

I belive pbsmrtpipe only strictly needs pbcore 1.2.3. However, if you run any of the tests in testkit-jobs from pysiv2 or use any test data files from internal SIV locations, these will fail due to changelist 161777 which has several updates to the BAM spec (3.0.1) which require pbcore 1.2.4. 

Martin suggested pointing to https://github.com/PacificBiosciences/pbcore/commits/p4-master and explained that there are external users that are pulling from master (e.g., Mark) that is preventing preventing github master to being synced with perforce. The new 1.2.4 changes are backward incompatible which will cause breakage on their end. 

This would mean there are 3 version of pbcore; github master (159576), github p4-master (161777)  and perforce (162003).

Not thrilled with the solution of pointing to p4-master, but this might be the only solution at this point. 

Can you or Martin keep p4-master and perforce in sync? This would probably be really helpful.

**Comment by pb-cdunn** [comment]
> Can you or Martin keep p4-master and perforce in sync? This would probably be really helpful.

That's not a problem. And I'll update it with the latest from p4 in a moment.

But what about pbcommand? PB_REQUIREMENTS.txt pulls the tip of master, which is 0.2.16. REQUIREMENTS.txt pulls 0.2.15 (or latest, after your fix in 143) from pypi. So which version does this test end up with? I think you need to remove the pbcommand version number from REQUIREMENTS.txt. I'll test both theories here...

**Comment by natechols** [comment]
After that fix, it should end up with version 0.2.16.

**Comment by pb-cdunn** [comment]
"end up with"? What if 0.2.16 is not in pypi? Then which does it get?

But first, I am trying your other idea:
```
Obtaining pbcore from git+git://github.com/PacificBiosciences/pbcore/tree/p4-master#egg=pbcore (from -r PB_REQUIREMENTS.txt (line 6))
  git clone in /home/ubuntu/virtualenvs/venv-2.7.9/src/pbcore exists with URL git://github.com/PacificBiosciences/pbcore.git
  The plan is to install the git repository git://github.com/PacificBiosciences/pbcore/tree/p4-master
What to do? (s)witch, (i)gnore, (w)ipe, (b)ackup 
```
Unless there is a way to answer that question via REQUIREMENTS.txt, we might have to clear the cache.

**Comment by pb-cdunn** [comment]
I'll try the `@` notation for the branch...

**Comment by pb-cdunn** [comment]
Hmm. It's suddenly using `python setup.py install` instead of the `pip install` commands. Weird. Did you change something?

**Comment by pb-cdunn** [comment]
```
Using /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages
Searching for pbcommand==0.2.8
Best match: pbcommand 0.2.8
Adding pbcommand 0.2.8 to easy-install.pth file
```
Curiouser and curiouser.

**Comment by pb-cdunn** [comment]
I took your `<` `>` fix, and now:
```
Requirement already satisfied (use --upgrade to upgrade): pbcommand>=0.2.15 in /home/ubuntu/virtualenvs/venv-2.7.9/src/pbcommand (from -r REQUIREMENTS.txt (line 4))
```
So it's keeping 0.2.16 from github. But if 0.2.17 happens to be in pypi, it will use that instead of the tip of master, if master is only 0.2.16.

Anyway, it does work with this. I'm curious why I have trouble replicating this locally, even when I switch to the master pbcore branch.

**Comment by pb-cdunn** [comment]
If I rebase this improvement again, will somebody actually consider merging it?

**Comment by mhsieh** [comment]
Close this for now, I will steal this PR and make one internally.

**Pull request closed without merging**
