### PR TITLE
Support for chunked IsoSeq pipeline

### PR DESCRIPTION
**Pull request by natechols**
This adds a gather for arbitrary statistics in JSON format (pbtranscript output), plus a workaround for empty ContigSets, both required for IsoSeq to work.

### CODE REVIEW

**Comment by mpkocher** [comment]
Is it possible for the json 'model'  to use the standard pacbio Report data model? The report model is defined in pbcommand so every tool has access to the IO layers.

The 'report 'Attribute' data model could be used to store the metrics. Tables could also be used (or generated at the merge step). The json 'model' is overlapping quite a bit with that model. Having a report would allow the display of the metrics (UI) as well as being the common data model to be consumed by other tools (e.g., pbtrends).

**Comment by natechols** [comment]
I do not know how straightforward the model change would be but it's definitely a much better plan than my arbitrary dictionary.  Will take a look tomorrow or Friday.

**Comment by mpkocher** [comment]
Can you post a gist of an example file?

**Comment by natechols** [comment]
https://gist.github.com/natechols/a1d2ae2a6b8021bd728c

**Comment by mpkocher** [comment]
Here's the converted value.

https://gist.github.com/mpkocher/f6d24468a83121d9ea60

When you do the report merge, you could create a report Table that has the individual chunks (in addition to merging the attributes).

**Comment by natechols** [comment]
Perfect, this even gives me a way to put the labels in there (replacing the current 'name').  This meshes well with some changes I'll need to make to pbreports anyway, so I will do the conversion ASAP.

**Comment by mpkocher** [comment]
I've update that gist with a table example to show how the Table API works.

There's an html tool in pbsmrtpipe, pbtools-report, but it's not completely working as expected. But it does generate html. 

```
$> pbtools-report merged-report.json -o merged.html
```
This isn't really a public interface, it's just something that was hacked together to generate some view of the data. In 2.3 this was done via the java code in SMRT Portal.

**Pull request merged**
