### PR TITLE
replace "accuracy" with "concordance" where appropriate

### PR DESCRIPTION
**Pull request by ben-lerch**

### CODE REVIEW

**Comment by mpkocher** [comment]
Is this changed within pbalign? I don't see any commits to pbalign for these changes. 

The TC JSON files shouldn't be edited by hand. The recommended model is to re-emit the TC directly from pbalign, then copy the new TCs into pbsmrtpipe.

This should probably be documented if it's not already.

**Comment by natechols** [comment]
Just to add to what Michael said, if you don't modify pbalign and someone else later updates pbalign and regenerates the tool contracts, these changes will be overwritten.

**Comment by ben-lerch** [comment]
OK. Maybe we should just go ahead and completely transition pbalign over to the term "concordance" as well. Doing it halfway would be a very temporary solution anyway, right?

**Comment by ben-lerch** [comment]
if we want to just completely purge pbalign of 'accuracy', i have a PR for it: https://github.com/PacificBiosciences/pbalign/pull/45

**Comment by natechols** [comment]
pbalign isn't our code.  we shouldn't change anything that doesn't impact smrtlink without discussion with Jim's group, and I don't think this is a high priority right now anyway.

**Comment by ben-lerch** [comment]
https://github.com/PacificBiosciences/pbalign/pull/46

**Pull request merged**
