### PR TITLE
use header-aware gff merging function in pbcore.io

### PR DESCRIPTION
**Pull request by natechols**
This works for me using latest pbcore - I suspect CircleCI may choke on it (assuming the relevant test gets run).

### CODE REVIEW

**Comment by mpkocher** [comment]
Which version of pbcore do these changes depend on?

**Comment by natechols** [comment]
1.2.4, which is current in p4 but not GH or PyPI.

**Comment by mpkocher** [comment]
Any chance of getting pbcore updated on GH before merging this? 

Probably a good idea to update the pbsmrtpipe Req.txt file to require pbcore >=1.2.4 as well.

**Comment by natechols** [comment]
I hope GH pbcore can be updated soon but I think that's Dave's department.  We will need to update it anyway once the BAM spec update is added so we should probably wait until then.  (This fix isn't critical but the missing header does make testing difficult.)

**Comment by natechols** [comment]
Closing this, will revisit later.

**Pull request closed without merging**
