### PR TITLE
pbcommand version bump

### PR DESCRIPTION
**Pull request by pb-cdunn**
These are cluttering up my local repo, while I work pipeline changes locally.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Interesting. I tried the new "Squash and Merge". I don't like it. It didn't just squash the commits within the merge; it also squashed the merge-commit itself. So there is no back-reference to this Pull-Request. I guess that's fine if we use Issues, but not in this case.

**Comment by natechols** [comment]
Good to know - it's probably worth letting the other developers know too in case anyone else is tempted to try it.

**Comment by pb-cdunn** [comment]
Probably nobody else will notice it. The default works fine. This is just a note in case a discussion arises someday.

**Comment by natechols** [comment]
I was actually very tempted to use it myself, for those frequent situations when I have to make 4 additional trivial commits to get the CircleCI tests to work.  Definitely won't now, though.

**Pull request merged**
